default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reviewers_development
  username: reviewers
  host: localhost
  password: <%= Rails.application.credentials.dig(:development, :database_password) %>

test:
  <<: *default
  database: reviewers_t
  username: reviewers
  host: localhost
  password: <%= Rails.application.credentials.dig(:development, :database_password) %>

production:
  <<: *default
  database: reviewers_production
  username: reviewers
  password: password 
  password: <%= Rails.application.credentials.dig(:production, :database_password) %>
